
package br.com.caelum.estoque.cliente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EstoqueWSClient", targetNamespace = "http://ws.estoque.caelum.com.br/", wsdlLocation = "http://localhost:8080/estoquews-servidor/teste?wsdl")
public class EstoqueWSClient
    extends Service
{

    private final static URL ESTOQUEWSCLIENT_WSDL_LOCATION;
    private final static WebServiceException ESTOQUEWSCLIENT_EXCEPTION;
    private final static QName ESTOQUEWSCLIENT_QNAME = new QName("http://ws.estoque.caelum.com.br/", "EstoqueWSClient");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/estoquews-servidor/teste?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ESTOQUEWSCLIENT_WSDL_LOCATION = url;
        ESTOQUEWSCLIENT_EXCEPTION = e;
    }

    public EstoqueWSClient() {
        super(__getWsdlLocation(), ESTOQUEWSCLIENT_QNAME);
    }

    public EstoqueWSClient(WebServiceFeature... features) {
        super(__getWsdlLocation(), ESTOQUEWSCLIENT_QNAME, features);
    }

    public EstoqueWSClient(URL wsdlLocation) {
        super(wsdlLocation, ESTOQUEWSCLIENT_QNAME);
    }

    public EstoqueWSClient(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ESTOQUEWSCLIENT_QNAME, features);
    }

    public EstoqueWSClient(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EstoqueWSClient(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EstoqueWS
     */
    @WebEndpoint(name = "EstoqueWSClientPort")
    public EstoqueWS getEstoqueWSClientPort() {
        return super.getPort(new QName("http://ws.estoque.caelum.com.br/", "EstoqueWSClientPort"), EstoqueWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EstoqueWS
     */
    @WebEndpoint(name = "EstoqueWSClientPort")
    public EstoqueWS getEstoqueWSClientPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.estoque.caelum.com.br/", "EstoqueWSClientPort"), EstoqueWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ESTOQUEWSCLIENT_EXCEPTION!= null) {
            throw ESTOQUEWSCLIENT_EXCEPTION;
        }
        return ESTOQUEWSCLIENT_WSDL_LOCATION;
    }

}
